#!/bin/bash
function send_log(){
CHATID="5795571992"
KEY="6386703502:AAGiUjNES9aXxBWzuqNTiqDBDqd0uLcGFAs"
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIF MULTI LOGIN SSH ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Limit IP  : </code><code>$iplimit</code>
<code>Login IP  : </code><code>$cekcek</code>
<code>────────────────────</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
mulog=$(mesinssh)
date=$(date)
data=( `ls /etc/limit/ssh/ip`);
for user in "${data[@]}"
do
iplimit=$(cat /etc/limit/ssh/ip/$user)
cekcek=$(echo -e "$mulog" | grep $user | wc -l);
if [[ $cekcek -gt $iplimit ]]; then
egrep "^$user" /etc/passwd >/dev/null
passwd -l $user
systemctl restart ws
send_log
else
echo > /dev/null
fi
sleep 0.1
done
